global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'diabetes_app'
    static_configs:
      - targets: ['diabetes_app:5000']   # service name 'app' inside compose network
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']