apiVersion: v1
kind: Pod
metadata:
  name: diabetes-ml
spec:
  containers:
    - name: diabetes-ml
      image: diabetes-ml
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: diabetes-ml
          mountPath: /app/storage
  volumes:
    - name: diabetes-ml
      persistentVolumeClaim:
        claimName: diabetes-ml

